#!/bin/bash

if [ $# -ne 1 ] #Check the number of parameters
then
  echo -e "Only for internal configuration.\nIf you want to execute, read the code and see the parameters.\nIt's super easy :)"
else
  if [ ! $USER = "root" ] #Check if the script was executed with root permissions
  then
    echo "You need root permissions"
    exit 0
  fi
  MAGIC="0 string EMP EMP packaged file, from Linux" #The magic configuration
  MAGIC2="!:mime application/emp" #The magic configuration
  if [ $1 = "ins" ] #Put the magic configuration in the file /etc/magic
  then
    if [ -z "$(grep -w "$MAGIC" /etc/magic)" -a -z "$(grep -w "$MAGIC2" /etc/magic)" ] #Check if the configuration exists
    then
      echo -e "$MAGIC\n$MAGIC2" >> /etc/magic #Add the line
    fi
  elif [ $1 = "uins" ] #Remove the magic configuration :'(
  then
    if [ -n "$(grep -w "$MAGIC" /etc/magic)" -a -n "$(grep -w "$MAGIC2" /etc/magic)" ] #Check if the configuration exists
    then
      MAGICSED="!:mime application\/emp" #Added the \ because the sed command doesn't understand the character /
      sed -i "/$MAGIC/d" /etc/magic #Remove the line
      sed -i "/$MAGICSED/d" /etc/magic #Remove the line
    fi
  else
    echo "$1 not admited"
  fi
fi
exit 0
